wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.12
    start_time: 1688876697.486224
    t:
      1:
      - 1
      - 15
      - 55
      2:
      - 1
      - 15
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.13.10
      8:
      - 2
      - 5
